name: LeeesExploitFixer
version: 3.0
main: org.l2x9.l2x9core.Main
authors: [ 254n_m ]
description:  ${project.description}
website: https://www.l2x9.org
softdepend:
  - SalC1Dupe
commands:
  say:
    description: e
  open:
    description: e
  crash:
    description: e
  speed:
    description: e
  uuid:
    description: e
  uptime:
    description: e
  aef:
    description: e
  discord:
    description: e
  world:
    description: e
  help:
    description: e
  spawn:
    description: e
  toggleconnectionmessages:
    description: Toggles on / off connection messages for the sender of the command
    aliases:
      - tc
      - toggleconnection