name: LeeesExploitFixer
version: 3.0.2
main: ca.xera.leeesexploitfixer.Main
authors: [ 254n_m, Leeewith3Es ]
description:  ${project.description}
website: https://www.xera.ca
softdepend:
  - SalC1Dupe
commands:
  say:
    description: Broadcast a message to the server from the console.
  open:
    description: Open a players inventory (only works with OPed players)
  crash:
    description: Crash a player (use at your own risk)
  speed:
    description: Change the speed on how you walk (Oped players only)
  uuid:
    description: e
  uptime:
    description: Check server uptime
  lef:
    description: Main command
  discord:
    description: Discord command
  world:
    description: Teleport to another world
  help:
    description: Custom help command
  spawn:
    description: e
  toggleconnectionmessages:
    description: Toggles on / off connection messages for the sender of the command
    aliases:
      - tc
      - toggleconnection